BASE_URL = "https://www.saucedemo.com"
invalid_login_xlsx = "Data/invalid_login.xlsx"
valid_login_xlsx = "Data/valid_login.xlsx"
invalid_login2_xlsx = "Data/invalid_login2.xlsx"
USERNAME_ID = "user-name"
PASSWORD_ID = "password"
LOGIN_BUTTON_ID ="login-button"
ERROR_MESSAGE_XPATH = "//*[@id='login_button_container']/div/form/div[3]/h3"
USERNAME_PASSWORD_DONT_MATCH = "Epic sadface: Username and password do not match any user in this service"
USERNAME_REQUIRED = "Epic sadface: Username is required"
PASSWORD_REQUIRED = "Epic sadface: Password is required"
USER_LOCKED_OUT ="Epic sadface: Sorry, this user has been locked out."
ADD_TO_CHART_XPATH = "//*[@id='add-to-cart-sauce-labs-fleece-jacket']"
CART_CONTROL_XPATH ="//*[@id='shopping_cart_container']/a"
SUCCESS_CHECKOUT_XPATH = "//*[@id='checkout']"
FIRSTNAME_ID = "first-name"
LASTNAME_ID = "last-name"
POSTAL_CODE = "postal-code"
SUCCESS_CONTINUE_XPATH ="//*[@id='continue']"
SUCCESS_FINISH_XPATH = "//*[@id='finish']"
REMOVE_ITEM_XPATH = "//*[@id='remove-sauce-labs-fleece-jacket']"
REMOVE_ITEM = "Remove"
FINISH_MESSAGE_XPATH = "//*[@id='checkout_complete_container']/h2"
FINISH_MESSAGE = "Thank you for your order!"
FINISH_MESSAGE_XPATH2 ="//*[@id='header_container']/div[2]/span"
CHECKOUT_MESSAGE = "Checkout: Your Information"