# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalConstants as c

class TestValidpurchase():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_validpurchase(self):
    self.driver.get(c.BASE_URL)
    self.driver.maximize_window()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "user-name")))
    self.driver.find_element(By.ID, "user-name").click()
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "password")))
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    self.driver.find_element(By.XPATH, "//input[@id=\'login-button\']").click()
    self.driver.find_element(By.XPATH, "//button[@id=\'add-to-cart-sauce-labs-fleece-jacket\']").click()
    self.driver.find_element(By.LINK_TEXT, "1").click()
    self.driver.find_element(By.XPATH, "//button[@id=\'checkout\']").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'checkout_info_container\']/div/form/div").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "first-name")))
    self.driver.find_element(By.ID, "first-name").click()
    self.driver.find_element(By.ID, "first-name").send_keys("Zehra ")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "last-name")))
    self.driver.find_element(By.ID, "last-name").click()
    self.driver.find_element(By.ID, "last-name").send_keys("Temizel")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "postal-code")))
    self.driver.find_element(By.ID, "postal-code").click()
    self.driver.find_element(By.ID, "postal-code").send_keys("4455")
    self.driver.find_element(By.XPATH, "//input[@id=\'continue\']").click()
    self.driver.find_element(By.XPATH, "//button[@id=\'finish\']").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'checkout_complete_container\']").click()
    assert self.driver.find_element(By.XPATH, "//div[@id=\'checkout_complete_container\']/h2").text == "Thank you for your order!"
    self.driver.close()
  
